name: Build Spring Boot App

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: 'spring_boot_server'  # Specify the path to checkout the code

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
         
      
    - name: List contents of the directory
      run: ls -l
      working-directory: spring_boot_server

    - name: Build with Maven
      run: mvn clean install
      working-directory: spring_boot_server  # Set the working directory to spring_boot_server
      
    - name: Run tests
      run: mvn test
      working-directory: spring_boot_server  # Set the working directory to spring_boot_server
