name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'  # Specify the desired Node.js version as '15' for the latest
        
    - name: Install dependencies
      run: npm install
      working-directory: frontv2   # Set working directory to frontv2
      
    - name: Build
      run: npm run build
      working-directory: frontv2   # Set working directory to frontv2
 
