name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'  # Specify the desired Node.js version as '15' for the latest
        
    - name: Install dependencies
      run: npm install
      working-directory: frontv2   # Set working directory to frontv2
      
    - name: Build
      run: npm run build
      working-directory: frontv2   # Set working directory to frontv2
      
    - name: Deploy to hosting environment
      # Add your deployment step here, such as deploying to Azure, AWS, or another hosting provider
      # Example deployment command for Azure App Service:
      run: |
        az webapp deployment source config --name <app-name> --resource-group <resource-group-name> --branch main --repo-url https://github.com/<username>/<repository>.git
      env:
        AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
        AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
